#!/usr/bin/bash

filename=Akio-Screenshots-$(date +%F_%T)
# grim -g "$(slurp)" - | wl-copy
function selection(){
    # grim -g "$(slurp)" - | swappy -f - -o ~/Pictures/Screenshots/$filename.png
    grim -g "$(slurp)" - | swappy -o ~/Pictures/Screenshots/$filename.png
    dunstify -a "Screenshots Utils" -i ~/Pictures/Screenshots/$filename.png "Screenshots taken, saved on Path ~/Picture/Screenshots" -r 2000
}

# function full_screen(){
#     grim -g "$(slurp -o)" - | swappy -f - -o ~/Pictures/Screenshots/Akio-Screenshots-$(date +%F_%T).png
# }

function full_screen(){
    grim - | swappy -f - -o ~/Pictures/Screenshots/Akio-Screenshots-$(date +%F_%T).png
}

function delay(){
    geo="$(slurp)"
    sleep 3
    grim -g "$geo" - | swappy -f - -o ~/Pictures/Screenshots/Akio-Screenshots-$(date +%F_%T).png
}


doc() {
    echo "Usage:
    screenshot [Options]

    Options:
        selection       Screenshots the selected area
        full_screen     Screenshots the focussed screen
        all_screens     Screenshots all screens
        delay           Takes a screenshot of the selected area after 3 second"
}

case $1 in 
    selection) selection                ;;
    full_screen) full_screen            ;;
    all_screens) all_screens            ;;
    delay) delay                        ;;
    *) doc                              ;;
esac